### ISSUE TITLE
error TS2304: Cannot find name 'android'.

### ISSUE THREAD

**Issue by kfprimm** [alexziskind1/nativescript-oauth#1]
Hi there,

I'm trying to run the demo, but cannot build the package. Starting from a clean slate, I ran `git clone`, `npm install` in `/` & `/demo`, and then `npm run-script build`. I get the following error.

```
whitebase:nativescript-oauth kevin$ npm run-script build

> nativescript-oauth@0.9.0 build /Users/kevin/nativescript-oauth
> tsc

tns-oauth-webview-helper.android.ts(4,44): error TS2304: Cannot find name 'android'.
tns-oauth-webview-helper.android.ts(32,47): error TS2503: Cannot find namespace 'android'.
tns-oauth-webview-helper.android.ts(39,32): error TS2503: Cannot find namespace 'android'.
tns-oauth-webview-helper.android.ts(39,78): error TS2503: Cannot find namespace 'android'.
tns-oauth-webview-helper.android.ts(50,33): error TS2503: Cannot find namespace 'android'.
tns-oauth-webview-helper.android.ts(63,19): error TS2503: Cannot find namespace 'android'.
```

I'm very new to NativeScript & TypeScript, so I haven't had any luck tracking down the issue. My environment:

**Mac OS X** 10.11.4
**node** v6.4.0
**TypeScript** 1.8.10
**tns** 2.2.1

If you could point me in the right direction, I'd appreciate it. I'm very interesting in Google integration and would to love to help test this plugin further.

Thanks!

**Comment by kfprimm** [comment]
Ok, so I did a little more experimentation & figured out that the log is just a warning. I was able to build the demo & run it. Cool!

**Comment by alexziskind1** [comment]
Thanks for noticing this and for the PR!
