### ISSUE TITLE
Problems with the new format in NativeScript Projects

### ISSUE THREAD

**Issue by mjaime29** [alexziskind1/nativescript-oauth#10]
Hello, I'm was checking the oauth with facebook, but in the new structure the NativeScript projects there is not a "application.start()" method and app.ts file, in my case there is a "platformNativeScriptDynamic().bootstrapModule()" in main.ts, but not works put the code before this line, can you help me with this.

**Comment by alexziskind1** [comment]
Hi @mjaime29 .
.bootstrapModule() internally calls application.start(). Do you want to just place your nativescript-oauth initialization code before the call to .bootstrapModule().

Cheers.

**Comment by alexziskind1** [comment]
Please check out the new angular demo for details

**Comment by mjaime29** [comment]
Thank you so much, I will review it
