### ISSUE TITLE
NSHTTPCookieStorage not defined

### ISSUE THREAD

**Issue by DarriusWrightGD** [alexziskind1/nativescript-oauth#13]
nativescript@2.4.2
angular@2.2.1
windows 10
android device

After logging in through facebook, I then attempt to logout using 
tnsOAuthModule.logout()
and instead of successfully logging out I get the error "NSHttpCookieStorage is not defined". Any ideas?

**Comment by alexziskind1** [comment]
This has been fixed in 1.3.0
