### ISSUE TITLE
Unable to use issued Office365/AzureAD token in Web API

### ISSUE THREAD

**Issue by YvesCandel** [alexziskind1/nativescript-oauth#20]
The token issued by Microsoft when using this library isn't usable in any Web API solution to validate the logged in user.

For example: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-devquickstarts-dotnet-api

If you clone and run the solution: https://github.com/AzureADQuickStarts/AppModelv2-WebAPI-DotNet and fill in the Client ID in the web.config, then boot up an app with nativescript-oauth and use the same client ID there, an access token is issued which can't be validated by the API...

The only difference I notice between the token issued by, for example, a web application with adal.js and the token issued here, is that the audience appears to be different. Tokens issued to nativescript-oauth have the audience set to: "https://graph.microsoft.com" while other tokens always have it set to the guid of my app. (Client ID).

Any suggestions on what exactly is going on? All my users can log in perfectly fine, but we are completely unable to access any of our APIs, which makes our current Nativescript app completely useless until I can somehow solve this...

**Comment by YvesCandel** [comment]
Solved this by registering the app using the Azure portal rather than apps.dev.microsoft.com (so back to v1 instead of v2 endpoint), removing the /v2.0/ from the urls being used by this plugin and added "resource" with the client ID to the query string for the authorization code. This way the library works fine with the v1 endpoint, and both web and native application tokens are usable with our API.

**Comment by AAAnderson7301** [comment]
@YvesCandel  Can you give an example of your auth-helper-office365.js?

**Comment by YvesCandel** [comment]
@AAAnderson7301 I've changed the following things:

In auth-helper-office365.js:

```
_this.credentials = {
  authority: 'https://login.microsoftonline.com/common',
  authorizeEndpoint: '/oauth2/authorize',
  tokenEndpoint: '/oauth2/token',
  clientId: clientId,
  redirectUri: 'urn:ietf:wg:oauth:2.0:oob',
  scope: scopeStr
};
```

And in tns-oauth.js:

```
function getTokenFromCode(credentials, code) {
    var oauth2 = new TnsOAuth(credentials.clientId, credentials.clientSecret, credentials.authority, credentials.tokenEndpointBase, credentials.authorizeEndpoint, credentials.tokenEndpoint);
    var oauthParams = {
        grant_type: 'authorization_code',
        redirect_uri: credentials.redirectUri,
        response_mode: 'form_post',
        resource: credentials.clientId,
        nonce: utils.newUUID(),
        state: utils.newUUID()
    };
    return oauth2.getOAuthAccessToken(code, oauthParams);
}
function getTokenFromRefreshToken(credentials, refreshToken) {
    var oauth2 = new TnsOAuth(credentials.clientId, credentials.clientSecret, credentials.authority, credentials.tokenEndpointBase, credentials.authorizeEndpoint, credentials.tokenEndpoint);
    var oauthParams = {
        grant_type: 'refresh_token',
        redirect_uri: credentials.redirectUri,
        response_mode: 'form_post',
        resource: credentials.clientId,
        nonce: utils.newUUID(),
        state: utils.newUUID()
    };
    return oauth2.getOAuthAccessToken(refreshToken, oauthParams);
}
exports.getTokenFromRefreshToken = getTokenFromRefreshToken;
function getAuthUrl(credentials) {
    return credentials.authority + credentials.authorizeEndpoint +
        '?client_id=' + credentials.clientId +
        '&response_type=code' +
        '&redirect_uri=' + credentials.redirectUri +
        '&scope=' + credentials.scope +
        '&response_mode=query' +
        '&nonce=' + utils.newUUID() +
        '&state=' + utils.newUUID();
}
```

In my app's main.ts I do the following:

```
let o365InitOptions: tnsOAuthModule.ITnsOAuthOptionsOffice365 = {
  clientId: 'fill in app client ID from azure AD here',
  scope: ['User.Read', 'offline_access'],
};

tnsOAuthModule.initOffice365(o365InitOptions).then((result) => {
  result.credentials.authority = 'https://login.microsoftonline.com/' + 'fill in tenant ID from azure AD here';
});
```

Hope this helps you :) Perfect for an enterprise-only native application!

**Comment by alexziskind1** [comment]
Hey @YvesCandel ,
Thanks for sharing your solution. The o365 implementation was originally focused on the GraphAPI, but it definitely needs to be extended to support the types of scenarios that you're facing.

**Comment by AAAnderson7301** [comment]
@YvesCandel Thank you for sharing this. I ended up just upgrading my WebAPI and Angular2 Web App to support OAuth 2.0  [AD oAuth 2.0](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-appmodel-v2-overview) So that I can use the same Azure APP for my Native, Web and WebAPI

**Comment by YvesCandel** [comment]
@AAAnderson7301 The problem i faced was that the token issued to the v2.0 endpoint instead of the v1.0 endpoint (which is OAuth2 too) has the audience set to https://graph.microsoft.com which should be uour client is to use it on your api...

**Comment by AAAnderson7301** [comment]
@YvesCandel   How did you add the reply url of urn:ietf:wg:oauth:2.0:oob to portal.azure ? I tried your way as well but am getting 'reply address of urn:ietf:wg:oauth:2.0:oob no supported' and when I tried to add it to the portal it does not allow it because it is not a valid URL

**Comment by YvesCandel** [comment]
@AAAnderson7301 When you create the app, you have to choose "Native application". That one accepts that particular redirect uri. You can add normal urls too, so the native type can fit all your use cases. Won't need to register two apps.

**Comment by x3r10n** [comment]
I know it has been close for a while but I need help!
When I login everything is fine and I get my token from AD.
I can also login and use my website and the auth is working.

But when I send request from the native app to my API (regular MVC controller) I get this response :
{_body: Error: The certificate for this server is invalid. You might be connecting to a server that is prete…, status: 200, ok: true, statusText: "", headers: Headers…}


I made the modification mention by @YvesCandel 

Any idea why it say my certificate is invalid ?

**Comment by laur3d** [comment]
Is there any change that this could be integrated in the package somehow ? like AzureAdV1 endpoint ?

**Comment by YvesCandel** [comment]
If Azure AD is the only thing you're using, I've created a new plugin specifically for that: https://github.com/NavaraBV/nativescript-adal

**Comment by jferreirasetesys** [comment]
Why is this issue closed? It is still not possible to achieve this, or is it?
