### ISSUE TITLE
Unable to retrieve access and refresh token in android

### ISSUE THREAD

**Issue by shetty3456** [alexziskind1/nativescript-oauth#23]
failing in passing access and refresh token in android.
Everything works fine for iOS but fails in android.

Need help in passing tokens in android also.

"use strict"; var __extends = (this && this.__extends) || function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; function __() { this.constructor = d; } d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __()); }; 
var web_view_1 = require("ui/web-view"); var trace = require("trace"); var TnsOAuthWebViewHelper = (function (_super) 
{ __extends(TnsOAuthWebViewHelper, _super); function TnsOAuthWebViewHelper() { var _this = _super.call(this) || 
this; return global.__native(_this); } TnsOAuthWebViewHelper.initWithWebViewAndIntercept = function (wv, checkCodeIntercept) 
{ wv._webViewClient = TnsOAuthWebViewHelper.initWithView(wv, checkCodeIntercept); }; 
TnsOAuthWebViewHelper.initWithView = function (view, checkCodeIntercept) 
{ try { var client = new TnsOAuthWebViewHelper(); client._view = view; 
client._origClient = view._webViewClient; client._checkCodeIntercept = checkCodeIntercept; return client;
} catch (er) { console.dir(er); } }; TnsOAuthWebViewHelper.prototype.shouldOverrideUrlLoading = function (view, url){ if (trace.enabled) { trace.write("WebViewClientClass.shouldOverrideUrlLoading(" + url + ")", trace.categories.Debug); }return false; }; TnsOAuthWebViewHelper.prototype.onPageStarted = function (view, url, favicon){ _super.prototype.onPageStarted.call(this, view, url, favicon); if (this._view) { if (trace.enabled) { trace.write("WebViewClientClass.onPageStarted(" + url + ", " + favicon + ")", trace.categories.Debug); } 
this._view._onLoadStarted(url,web_view_1.WebView.navigationTypes[web_view_1.WebView.navigationTypes.indexOf("linkClicked")]); }}; TnsOAuthWebViewHelper.prototype.onPageFinished = function (view, url) { _super.prototype.onPageFinished.call(this, view, url);
if (this._view) { if (trace.enabled) { trace.write("WebViewClientClass.onPageFinished(" + url + ")", trace.categories.Debug); }this._view._onLoadFinished(url, undefined); this._checkCodeIntercept(this._view, null, url); } }; TnsOAuthWebViewHelper.prototype.onReceivedError = function () { var view = arguments[0]; if (arguments.length === 4) { var errorCode = arguments[1]; var description = arguments[2]; var failingUrl = arguments[3]; this._checkCodeIntercept(this._view, null, failingUrl);
_super.prototype.onReceivedError.call(this, view, errorCode, description, failingUrl); if (this._view) { if (trace.enabled) { trace.write("WebViewClientClass.onReceivedError(" + errorCode + ", " + description + ", " + failingUrl + ")",trace.categories.Debug); } this._view._onLoadFinished(failingUrl, description + "(" + errorCode + ")"); } } else { var request = arguments[1]; var error = arguments[2]; this._checkCodeIntercept(this._view, error);
_super.prototype.onReceivedError.call(this, view, request, error); if (this._view) { if (trace.enabled) 
{ trace.write("WebViewClientClass.onReceivedError(" + error.getErrorCode() + ", " + error.getDescription() + ", " + (error.getUrl && error.getUrl()) + ")", trace.categories.Debug); } this._view._onLoadFinished(error.getUrl && error.getUrl(),
error.getDescription() + "(" + error.getErrorCode() + ")"); } } };
return TnsOAuthWebViewHelper; }(android.webkit.WebViewClient)); exports.TnsOAuthWebViewHelper = TnsOAuthWebViewHelper;

**Comment by alexziskind1** [comment]
Is this JavaScript generated from your TypeScript code?
What is your error message?
What are you trying to connect to?
What versions are you using of 
OS?
NativeScript CLI?
Do you have the codebase available?

**Comment by shetty3456** [comment]
Its a javascript code
Error: When we are trying to log into the application access token is null.
Trying to connect to : our company authentication system in android. [Same code base works fine in iOS]
Os: macOS Siera
Nativescript : 2.5.0
codebase: 
In auth-helper-XYZ.js
"use strict";
var __extends = (this && this.__extends) || function (d, b) {
        for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
var auth_helper_1 = require('./auth-helper');
var AuthHelperXYZ = (function (_super) {
    __extends(AuthHelperXYZ, _super);
    function AuthHelperXYZ(clientId, clientSecret, scope) {
        _super.call(this);
        var scopeStr = scope.join('%20');
        this.credentials = {
            authority: 'https://cloudsso.xyz.com/as',
            authorizeEndpoint: '/authorization.oauth2',
            tokenEndpoint: '/token.oauth2',
            clientId: clientId,
            clientSecret: clientSecret,
            redirectUri: 'urn:ietf:wg:oauth:2.0:oob',
            scope: scopeStr
        };
    }
    AuthHelperXYZ.prototype.logout = function (successPage) {
        var cookieDomains = [".xyz.com"];
        return this._logout(successPage, cookieDomains);
    };
    return AuthHelperXYZ;
}(auth_helper_1.AuthHelper));
exports.AuthHelperXYZ = AuthHelperXYZ;


In index.js:

function initXYZ(options) {
    return new Promise(function (resolve, reject) {
        console.log(options.scope);
        try {
            if (exports.instance !== null) {
                reject("You already ran init");
                return;
            }
            exports.instance = new auth_helper_xyz_1.AuthHelperXYZ(options.clientId, options.clientSecret, options.scope);
            resolve(exports.instance);
        }
        catch (ex) {
            console.log("Error in AuthHelperXYZ.init: " + ex);
            reject(ex);
        }
    });
}
exports.initXYZ = initXYZ;

In tns-oauth.js
if (codeStr) {
                        try {
                            getTokenFromCode(credentials, codeStr)
                                .then(function (response) {
                                tns_oauth_token_cache_1.TnsOAuthTokenCache.setToken(response);
                                console.dump(successPage);
                                if (successPage && navCount === 0) { // this condition always fails.
                                    var navEntry = {
                                        moduleName: successPage,
                                        clearHistory: true
                                    };
                                    frameModule.topmost().navigate(navEntry);
                                }
                                else {
                                    console.log("Jumped here"); // its jumping here
                                    frameModule.topmost().goBack();
                                }
                                navCount++;
                                resolve(response);
                            })
                                .catch(function (er) {
                                reject(er);
                            });
                        }

**Comment by alexziskind1** [comment]
It looks like you're trying to implement your own provider. This is great, but I don't have access to whatever it is you are using as the provider. 
Sorry I can't help anymore.
