### ISSUE TITLE
Can i use this for Github and Bitbucket?

### ISSUE THREAD

**Issue by ycpatel813** [alexziskind1/nativescript-oauth#25]
Hi, 
I am using your auth and it work fine for Google and Facebook but need now social login using github and bitbucket for NaativeScript. Am i use this package? If yes may i get some idea ? 

Thanks.

**Comment by alexziskind1** [comment]
This plugin would need to be extended to support GitHub and Bitbucket. Currently there is no built in classes to handle these providers, but it shouldn't be hard to add. If you submit a pull request with them implemented, that would be super.

**Comment by Rwrf9** [comment]
@ycpatel813 
Hi, it's work for Google? 
Google says me "disallowed_useragent" ... 
Maybe a way to inject a custom useragent on webview? 
thx
