### ISSUE TITLE
How to obtain for facebook auth other scope data like email, public_profile infos....

### ISSUE THREAD

**Issue by noetius** [alexziskind1/nativescript-oauth#26]
Hello,
my request is more like a question than a bug or a feature request i suppose, in the docs there are no explanations about obtaining scope data like email and public_profile after getting the access token.
Maybe I'm looking for in the wrong places, but if there's a way to do this, could someone kindly give me a hand?

Thanks.

**Comment by ryuker16** [comment]
```
var facebookInitOptions: tnsOAuthModule.ITnsOAuthOptionsFacebook = {
    clientId: '********************',
    clientSecret: '****************',
    scope: ['email', 'public_profile'],
};
```
there are more option scopes like friend's list.

Afterwards you attach the token to a get request to facebook graph api to get stuff like user pictures or profile info.

https://developers.facebook.com/docs/graph-api/overview

**Comment by noetius** [comment]
Thanks for your reply, it should not be a problem using this approach, I was just wondering if it might not be useful to directly integrate a helper in order to make these data available on request, but it is just an idea for the moment, maybe it could be evaluated as a feature request, when it will be possible.

**Comment by alexziskind1** [comment]
Hi @noetius . That's a great suggestion.
