### ISSUE TITLE
UAA wrapper?

### ISSUE THREAD

**Issue by TimAtExc** [alexziskind1/nativescript-oauth#28]
Hi, any plans for a UAA wrapper?  If not, would like to perhaps make a contribution.

**Comment by alexziskind1** [comment]
Hi Tim,

No such plans so far. Definitely will test any contribution you'd like to
add

Thanks

On Mar 7, 2017, at 11:51 AM, TimAtExc <notifications@github.com> wrote:

Hi, any plans for a UAA wrapper? If not, would like to perhaps make a
contribution.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/alexziskind1/nativescript-oauth/issues/28>, or mute the
thread

**Comment by TimAtExc** [comment]
Hi Alex, I'm working on a UAA flavor of this plugin - I've followed your pattern in creating a provider-specific helper but it seems that when we get down to the oauth/token route UAA needs an Authorization header.  Can you see a clean way to get this behavior to trickle down to that level?

Here's a section of tns-oauth.ts:

`    public getOAuthAccessToken(code, params): Promise<TnsOAuthModule.ITnsOAuthTokenResult> {
        //console.log('called TnsOAuth.getOAuthAccessToken');
        var params = params || {};
        params['client_id'] = this._clientId;
        if (this._clientSecret && this._clientSecret != '') {
            params['client_secret'] = this._clientSecret;
        }

        var codeParam = (params.grant_type === 'refresh_token') ? 'refresh_token' : 'code';
        params[codeParam] = code;

        var post_data = querystring.stringify(params);
        var post_headers = {
            **'Authorization': 'Basic XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',**
            'Content-Type': 'application/x-www-form-urlencoded'
        };`


If I add the Basic Authorization header above, it works, I get a token back. Any ideas on the cleanest way to accomplish this?

Thanks!

**Comment by TimAtExc** [comment]
I'm going down the route of using the customHeaders variable to inject the Authorization header into the request...

**Comment by alexziskind1** [comment]
@TimAtExc I haven't looked into it, but when I thought about passing different Authz headers, I imaged it would be similar to overriding the headers value with an optional passed in headers collection.

**Comment by alexziskind1** [comment]
Uaa is now included
