### ISSUE TITLE
Does not work - error TnsOAuthOptionsOffice365 has no exported member

### ISSUE THREAD

**Issue by nigel-dewar** [alexziskind1/nativescript-oauth#3]
Hi Just giving heads up that I installed and following instructions correctly,

Using the nativescript groceries demo project also.

I get this error when trying to run . 

Found peer TypeScript 1.8.10
app/main.ts(9,38): error TS2305: Module '"C:/_learning/sample-Groceries/node_mod
ules/nativescript-oauth/index"' has no exported member 'TnsOAuthOptionsOffice365
'.
TypeScript compiler failed with exit code 1

is TnsOAuthOptionsOffice365 still valid?  It is complaning in my typescript editor 'vs code' that it is incorrect. and has no exported member.

**Comment by nigel-dewar** [comment]
It looks like one must use 
var o365InitOptions : tnsOAuthModule.ITnsOAuthOptionsOffice365

 when setting up. does your instructions need updating?

**Comment by alexziskind1** [comment]
Yep, you're correct with the second usage. The docs have been updated.
