### ISSUE TITLE
Adding linked in support how to test it

### ISSUE THREAD

**Issue by nicolam1** [alexziskind1/nativescript-oauth#31]
Alex,
I'm adding linkedin support on a separate Fork but when I run the demo apps if I try to use `npm link` I get all kinds of errors. If I push my code and load it from a repo for some reason the `ts` files do not get built into `js`. How do you go about building the files and pushing them to npm?

**Comment by alexziskind1** [comment]
Check out the updated readme file, specifically the last section on Contributing.
I don't  use npm link, but use the manual process described there. Also, you won't be able to push to NPM, I'll have to do it once I approve your PR.
