### ISSUE TITLE
Not authenticate 

### ISSUE THREAD

**Issue by 16082016platform** [alexziskind1/nativescript-oauth#36]
Hi.

I followed the steps with an application created from the browser with Telerik Platform and Nativescript. The errors are not logged, but while the functions: ensureValidToken () or login (), is redirected to a facebook page that indicates that it was not logged on error way, see the two images attached.

This is the project. It only has a button that calls the facebook login function.
https://github.com/16082016platform/recargas.git
Thank you.
![whatsapp image 2017-04-15 at 19 37 45](https://cloud.githubusercontent.com/assets/21073590/25067981/c5c81966-2219-11e7-9ca2-ef83377ead0e.jpeg)
![whatsapp image 2017-04-15 at 19 35 46](https://cloud.githubusercontent.com/assets/21073590/25067982/c5e1e44a-2219-11e7-99ce-c91973f16d23.jpeg)

**Comment by Yamilquery** [comment]
I got the same error. Then log in with Facebook in my browser and now I get it. 

<img width="363" alt="captura de pantalla 2017-06-03 a la s 17 17 47" src="https://cloud.githubusercontent.com/assets/6020065/26757440/cbb3a416-4880-11e7-8bab-0ebe34acf877.png">

I hope someone has a solution

**Comment by Yamilquery** [comment]
I found the solution. Enter your Facebook application settings and delete the Android and IOS platform, just leave the Web and point the redirect_url to https://www.facebook.com/connect/login_success.html

Enjoy!

**Comment by alexziskind1** [comment]
Thanks for posting the solution @Yamilquery
