### ISSUE TITLE
Angular Support

### ISSUE THREAD

**Issue by hypery2k** [alexziskind1/nativescript-oauth#4]
Did the plugin work with angular in native script?

**Comment by alexziskind1** [comment]
Yes, this plugin is independent of the UI framework layer. You can call it from your Angular 2 based NativeScript apps

**Comment by RooFi07** [comment]
So, how I can logout from app if successPage is required? Angular2 + NS has different navigation, without ui/frame, so I can't share module name.

**Comment by alexziskind1** [comment]
I've added a demo-angular project as a sample. Please take a look. All this plugin does for you is the authentication part and provides you with an OAuth Access Token. It's up to you to handle navigation between your app's login and other pages.

**Comment by RooFi07** [comment]
Thank you for your response. I checked sample, but I did not see used the logout method.

**Comment by alexziskind1** [comment]
Please get the 1.2.0 version, I've made the logout page optional.
