### ISSUE TITLE
Implementing custom servers?

### ISSUE THREAD

**Issue by jaypan** [alexziskind1/nativescript-oauth#5]
I'm running oauth as the backend on our own server, is there a way to use this module to authenticate with that? Are there instructions somewhere?

Also, will this work with nativescript 2.3.0? I'm brand-new to nativescript, but the instructions seem to be for a different version.

**Comment by alexziskind1** [comment]
Since the oauth plugin is following standard OAuth flows, then theoretically you should be able to use your own authentication server. The 2.3.0 version works fine with the plugin.
