### ISSUE TITLE
IOS 11.1 - null object error

### ISSUE THREAD

**Issue by laur3d** [alexziskind1/nativescript-oauth#59]
I have followed the video tutorial to the letter, and everything thing works nice and dandy on android, but not on IOS 11.1.

The error I'm getting is: 

`
 null is not an object (evaluating 'exports.instance.login')
`

the same is also with ensureValidToken

**Comment by alexziskind1** [comment]
There was an update to the delegate used by NativeScript webview widget. This has been fixed, please try again with the latest version.
