### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by armackey** [alexziskind1/nativescript-oauth#60]
When I press login I get 'Error' 'Not Logged In: You are not logged in. Please login and try again.' No option to enter my facebook credentials.

Followed the tutorial on youtube. Also, followed the docs. Not sure what I'm missing here. Thanks!

**Comment by BenJaminBMorin** [comment]
I had the same issue.  I accidentally had an entry in the “Valid OAuth Redirect URIs” field which caused the problem.

**Comment by alexziskind1** [comment]
Hi folks. Please use the new NativeScript-oauth2 plugin instead. It addresses some security concerns with Open Id certified providers. Facebook doesn’t support OpenId, so it would use a similar flow to the current Oauth plugin. The problem you are describing should be resolved by altering your facrbook app configuration at your Facebook developer account.
