### ISSUE TITLE
Show Empty Screen in IOS

### ISSUE THREAD

**Issue by LSmint** [alexziskind1/nativescript-oauth#62]
When i call tnsOAuthModule.ensureValidToken() function, it takes me to an empty screen with following trace log:
file:///app/tns_modules/nativescript-oauth/tns-oauth.js:134:20: LOGIN PAGE URL = https://www.facebook.com/dialog/oauth?client_id=1675108149222641&response_type=code&redirect_uri=https://www.facebook.com/connect/login_success.html&scope=email%20public_profile&response_mode=query&nonce=749e8491-05c5-4e1c-9d66-ce652cc53364&state=abcd

Appreciate if anyone can help me about this

**Comment by lumayara** [comment]
Hi. I am having the same issue. I am in the screen to type my password, but after I click Sign in, nothing happens and I only see this in my console.
