### ISSUE TITLE
Problem with Login Microsoft OAuth- Not working

### ISSUE THREAD

**Issue by lumayara** [alexziskind1/nativescript-oauth#67]
Hi, I am trying to login in my app but it's is not working. I have gotten a couple of error messages like: URI does not match with registered reply, etc.. But now my screen does not even change and I am stuck in the login page and no errors appear, not even in my console.
I registered the app in app.dev.microsoft.com as native app and followed the tutorial on youtube: www.youtube.com/watch?v=nwf928oFGCM
Here is my screen. I typed my login and password and it gives me this screen, but when I click accept nothing changes, the page stays there. Sometimes I will run the app and try to login with another account and it gets stuck in the part where I type my password and click in Submit, but nothing happens. The page is stuck. I am sure there is some error going on but I have no idea what it is because nothing shows up.
<img width="314" alt="screen shot 2018-03-23 at 3 20 25 pm" src="https://user-images.githubusercontent.com/8031814/37849523-6fc0543c-2eae-11e8-8ad4-55a0619f6609.png">
<img width="297" alt="screen shot 2018-03-23 at 3 28 39 pm" src="https://user-images.githubusercontent.com/8031814/37849717-272f7968-2eaf-11e8-90eb-e638f0aef7bf.png">

**Comment by alexziskind1** [comment]
Hi @lumayara . The plugin has been updated and I think after the updated plugin, you're not able to sign in.

**Comment by lumayara** [comment]
Yep. I uninstalled everything and installed again and it worked. Thank you, Alex!
