### ISSUE TITLE
How to implement using Angular version of nativescript project

### ISSUE THREAD

**Issue by nigel-dewar** [alexziskind1/nativescript-oauth#7]
Hi Alex,

how does one implement using the angular version of a nativescript project. Im looking at the instructions are there is really no way I can reference where stuff is supposed to go.

Could you please update instructions for using angular version of nativescript project?

cheers

**Comment by alexziskind1** [comment]
Hi Nigel. This youtube video might be able to help you with the setup: https://www.youtube.com/watch?v=nwf928oFGCM

**Comment by alexziskind1** [comment]
Hi again. Perhaps you're also wondering WHERE you should place the initialization code.
In the Angular version of the app, you have a line in main.ts where you call .bootstrapModule(). You should place your initialization code before this call.
Hope this helps.

**Comment by nigel-dewar** [comment]
Ok thanks i will try
