### ISSUE TITLE
npm latest release (2.1.3) does not contain all files

### ISSUE THREAD

**Issue by Eonfuzz** [alexziskind1/nativescript-oauth#76]
Please see the resolved download path (Or just npm install nativescript-oauth):
https://registry.npmjs.org/nativescript-oauth/-/nativescript-oauth-2.1.3.tgz

It only contains index.d.ts and tns-oauth-interfaces.d.ts

Please also supply all the other needed files in the dist, thanks.

Edit:

I noticed you have a !*.js in the .npmignore - looks like this hasn't worked or was submitted without *.js files.

**Comment by alexziskind1** [comment]
Thanks for the heads up. This is fixed
