### ISSUE TITLE
Azure AD login does nothing after submitting correct credentials

### ISSUE THREAD

**Issue by raygerrard** [alexziskind1/nativescript-oauth#78]
After entering the correct username and password and submitting the form nothing happens.

Hitting the return key or the "Sign in" button doesn't go anywhere. If the wrong password is entered it does provide an error message.

The success and failure callbacks are not called and the page does not redirect anywhere.

The same username and password form is still present with the fields still completed.

**Comment by alexziskind1** [comment]
Please try the latest version.

**Comment by raygerrard** [comment]
I am using version 2.1.7 and the issue is still happening.

**Comment by charsleysa** [comment]
@raygerrard have you double checked that you have setup the redirectUri correctly?
This is usually the problem when the none of the callbacks are executed.

**Comment by alexziskind1** [comment]
This is usually a problem with the Azure AD config. It’s pissible that it has been configured as a native app in Azure with a custom URL scheme. 
To be able to support scenarios with custom URL schemes, please use the new NativeScript-Oauth2 plugin.
