### ISSUE TITLE
Android facebook authentication problem

### ISSUE THREAD

**Issue by naturalfreak** [alexziskind1/nativescript-oauth#8]
Android facebook authentication is not working.

`11-21 23:04:24.673 26520 26520 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>
11-21 23:04:24.673 26520 26520 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>
11-21 23:04:24.677 26520 26520 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.ServiceWorkerControllerAdapter>
11-21 23:04:24.678 26520 26520 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.ServiceWorkerControllerAdapter>
chromium: [INFO:library_loader_hooks.cc(151)] Chromium logging enabled: level = 0, default verbosity = 0
11-21 23:04:24.728 26520 26520 I cr_BrowserStartup: Initializing chromium process, singleProcess=true
chromium: [ERROR:interface_registry.cc(99)] Failed to locate a binder for interface: autofill::mojom::AutofillDriver
`

![15139390_1384141264949690_1402398905_n](https://cloud.githubusercontent.com/assets/11893674/20500724/562be430-b03f-11e6-8c8b-ced6c4d16a9b.png)

**Comment by nfourre** [comment]
Hi all,

@naturalfreak , I have the same problem in my app.

**Comment by srjt** [comment]
SOLUTION: I am having same issue. After debugging I found out that onPageFinished function in tns-oauth-webview-helper.android.js is not calling "_checkCodeIntercept" method. 
Adding "this._checkCodeIntercept(this._view, null, url);" to onPageFinished fixes the issue.
I tried generating pull request but could not compile the code locally.

**Comment by beagleknight** [comment]
@srjt You are totally right! I hope this can be solved soon. Can I help you with something?
