### ISSUE TITLE
Support for PKCE OAuth Flow

### ISSUE THREAD

**Issue by markballenger** [alexziskind1/nativescript-oauth#88]
PKCE "pixy" is the newer standard for properly securing OAuth2.0 flow for mobile devices. I see that custom provider support was added which is great, but it'd be nice to extend that to support PKCE as well to meet the modern mobile standard.

**Comment by alexziskind1** [comment]
Yes, this would be fantastic. Thanks for the suggestion.

**Comment by markballenger** [comment]
For anyone else interested or up for the challenge of adding PKCE support to this library, here is a lib that supports Azure ADAL, which utilizes PKCE
https://github.com/NavaraBV/nativescript-adal

**Comment by alexziskind1** [comment]
The new plugin called NativeScript-oauth2 replaces this plugin and has support for PKCE as well as the old webview style auth flows.
