### ISSUE TITLE
show a spinner between (the login button click to the facebook modal appearance )

### ISSUE THREAD

**Issue by Waseem-Isaac** [alexziskind1/nativescript-oauth#91]
I need to show a spinner between (the login button click until the facebook modal appearance-before get the token-) ) ,to handle the issues with the slow network connections connections.

where can I put the loader ?  
 tnsOAuthModule.ensureValidTokenFacebook()
    .then((token: string) => {
    }).catch(() => {
    });

**Comment by alexziskind1** [comment]
Hi Waseem. Please use the new NativeScript-oauth2 plugin. It had much better handling of login scenarios.

**Comment by Waseem-Isaac** [comment]
> Hi Waseem. Please use the new NativeScript-oauth2 plugin. It had much better handling of login scenarios.

thansk Alex , I will
